import { StyleSheet, Dimensions, Platform, StatusBar } from "react-native";
const { width, height } = Dimensions.get("window");

const getStyles = (colors: any) => StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  gradient: {
    flex: 1,
  },
  container: {
    flex: 1,
  },
  stickyHeader: {
    zIndex: 10,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  logo: {
    fontSize: 24,
    fontWeight: '900',
    color: colors.textLight,
  },
  searchWrapper: {
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBg,
    paddingHorizontal: 12,
    borderRadius: 12,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    height: 40,
    fontSize: 16,
    color: colors.text,
  },
  searchResults: {
    position: 'absolute',
    top: 45,
    left: 16,
    right: 16,
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  searchResultImage: {
    width: 40,
    height: 60,
    borderRadius: 4,
  },
  searchResultText: {
    marginLeft: 12,
    flex: 1,
  },
  searchResultTitle: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.text,
  },
  searchResultAuthor: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  clearButton: {
    padding: 8,
  },
  clearIconContainer: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.border,
    justifyContent: 'center',
    alignItems: 'center',
  },
  clearIcon: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: 'bold',
  },
  resultsList: {
    width: '100%',
  },
  noResultsContainer: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noResultsText: {
    color: colors.textSecondary,
    fontSize: 16,
    fontWeight: '500',
  },
  categoriesContainer: {
    paddingHorizontal: 16,
    marginBottom: 24,
    marginTop: 4,
  },
  categoryButton: {
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
    backgroundColor: colors.theme === 'dark' ? 'rgba(56, 189, 248, 0.12)' : colors.primary,
    borderWidth: 1.5,
    borderColor: colors.theme === 'dark' ? colors.tint : 'transparent',
  },
  categoryText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.theme === 'dark' ? colors.tint : colors.textLight,
  },
  section: {
    paddingHorizontal: 16,
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 28,
    fontWeight: '700',
    marginBottom: 16,
    color: colors.textLight,
    textShadowColor: 'black',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 0,
  },
  viewAllButton: {
    backgroundColor: colors.inputBg,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  viewAllText: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '500',
  },
  likesCount: {
    marginLeft: 8,
    marginRight: 4,
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
  },
  bookCard: {
    height: 275,
    width: 160,
    marginRight: 16,
    backgroundColor: colors.surface,
    borderRadius: 8,
    padding: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  bookCover: {
    width: 144,
    height: 156,
    borderRadius: 8,
    marginBottom: 8,
  },
  bookTitle: {
    fontSize: 18,
    paddingBottom: 4,
    fontWeight: '500',
    marginBottom: 4,
    color: colors.text,
  },
  bookAuthor: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  authorCard: {
    width: 120,
    alignItems: 'center',
    marginRight: 16,
    marginBottom: 16,
  },
  authorPhoto: {
    width: 80,
    height: 80,
    borderRadius: 40,
    marginBottom: 8,
  },
  authorName: {
    fontSize: 14,
    color: colors.text,
    textAlign: 'center',
    height: 40,
  },
  noAuthorsText: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: 20,
  },
  topBookCard: {
    flexDirection: 'row',
    marginBottom: 16,
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: colors.border,
  },
  topBookCover: {
    width: 60,
    height: 90,
    borderRadius: 6,
  },
  topBookInfo: {
    flex: 1,
    marginLeft: 12,
  },
  topBookTitle: {
    fontSize: 16,
    fontWeight: '500',
    marginBottom: 8,
    color: colors.text,
  },
  topBookMeta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  topBookMetaText: {
    fontSize: 12,
    color: colors.textSecondary,
    marginRight: 12,
  },
  topBookDetail: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  ratingContainer: {
    position: 'absolute',
    top: 0,
    right: 0,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  rating: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
  },
  dropdownOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
    paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight ? StatusBar.currentHeight + 65 : 95) : 105,
    paddingRight: 16,
  },
  dropdownContainer: {
    width: 250,
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    padding: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  dropdownTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingBottom: 6,
  },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 8,
  },
  dropdownItemActive: {
    backgroundColor: colors.theme === 'dark' ? colors.inputBg : '#E6F0FA',
  },
  dropdownItemText: {
    fontSize: 14,
    color: colors.textSecondary,
    fontWeight: '600',
  },
  dropdownItemTextActive: {
    color: colors.tint,
  },
});

export default getStyles;