import React, { useState } from 'react';
import { View, StyleSheet, TouchableOpacity, Text, ActivityIndicator, SafeAreaView, Platform, StatusBar, TextInput, Alert } from 'react-native';
import { useOrg } from '../../context/OrganizationContext';
import { useAuth } from '../../context/AuthContext';
import { useTheme } from '../../context/ThemeContext';
import { LogOut, ArrowLeft, Building2, KeyRound, Plus } from 'lucide-react-native';
import { LinearGradient } from 'expo-linear-gradient';
import axios from 'axios';
import Constants from 'expo-constants';

const API_URL = Constants.expoConfig?.extra?.apiUrl ?? '';

export default function OrgSelectionScreen({ navigation }: any) {
  const { memberships, loading, switchOrg, refreshOrgs } = useOrg();
  const { logout, user } = useAuth();
  const { colors } = useTheme();
  const styles = getStyles(colors);

  const [inviteCode, setInviteCode] = useState('');
  const [joining, setJoining] = useState(false);

  // SuperAdmin guard — redirect to their dedicated dashboard
  React.useEffect(() => {
    if (user?.globalRole === 'SuperAdmin') {
      navigation.replace('SuperAdmin');
    }
  }, [user]);

  const handleJoinByCode = async (codeToUse: string) => {
    const code = codeToUse.trim();
    if (!code) {
      Alert.alert('Error', 'Please enter a valid invite code.');
      return;
    }
    try {
      setJoining(true);
      const res = await axios.post(`${API_URL}/api/organizations/join-invite`, { inviteCode: code });
      if (res.data.status === 'Ok') {
        Alert.alert('Success', 'Successfully joined organization!');
        setInviteCode('');

        // Refresh context memberships
        await refreshOrgs();

        // Switch active org and redirect (Admin invites land in AdminScreen, others in MainApp)
        const orgId = res.data.data._id;
        const role = res.data.role;
        const success = await switchOrg(orgId);
        if (success) {
          if (role === 'Admin') {
            navigation.replace('AdminScreen');
          } else {
            navigation.replace('MainApp');
          }
        }
      }
    } catch (err: any) {
      Alert.alert('Error', err.response?.data?.message || 'Failed to join organization. Please verify the code.');
    } finally {
      setJoining(false);
    }
  };

  const hasWorkspaces = memberships.length > 0;

  // If SuperAdmin, show nothing while redirecting
  if (user?.globalRole === 'SuperAdmin') {
    return (
      <SafeAreaView style={styles.outerContainer}>
        <LinearGradient colors={colors.linearGradient} style={styles.gradient}>
          <View style={styles.loaderContainer}>
            <ActivityIndicator size="large" color="#fff" />
          </View>
        </LinearGradient>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.outerContainer}>
      <LinearGradient colors={colors.linearGradient} style={styles.gradient}>
        {hasWorkspaces && (
          <View style={styles.topBar}>
            <TouchableOpacity
              style={styles.backButton}
              onPress={() => navigation.goBack()}
            >
              <ArrowLeft color="#fff" size={22} />
            </TouchableOpacity>
            <Text style={styles.topBarTitle}>Join Workspace</Text>
            <View style={{ width: 44 }} />
          </View>
        )}
        <View style={styles.container}>

          <View style={styles.header}>
            {!hasWorkspaces && (
              <Text style={styles.title}>Welcome to Youth Room</Text>
            )}
            <Text style={styles.subtitle}>
              {hasWorkspaces
                ? "Enter the invite code generated by your organization admin to join a new workspace."
                : "Enter the invite code sent by your organization admin to join a workspace."
              }
            </Text>
          </View>

          {loading ? (
            <View style={styles.loaderContainer}>
              <ActivityIndicator size="large" color="#fff" />
              <Text style={styles.loaderText}>Loading workspaces...</Text>
            </View>
          ) : (
            <View style={styles.glassCard}>
              <View style={styles.iconWrapper}>
                <View style={styles.iconGlow}>
                  <Building2 color={colors.tint} size={32} />
                </View>
              </View>

              <View style={styles.inputContainer}>
                <Text style={styles.inputLabel}>Workspace Invite Code</Text>
                <View style={styles.inputWrapper}>
                  <KeyRound color={colors.tint} size={20} style={styles.inputIcon} />
                  <TextInput
                    style={styles.textInput}
                    value={inviteCode}
                    onChangeText={setInviteCode}
                    placeholder="Enter code (e.g. GRACE-1234)"
                    placeholderTextColor={colors.textSecondary + '80'}
                    autoCapitalize="characters"
                    autoCorrect={false}
                  />
                </View>
              </View>

              <TouchableOpacity
                style={styles.joinButton}
                onPress={() => handleJoinByCode(inviteCode)}
                disabled={joining}
              >
                <LinearGradient
                  colors={colors.linearGradient}
                  style={styles.gradientButton}
                  start={{ x: 0, y: 0 }}
                  end={{ x: 1, y: 0 }}
                >
                  {joining ? (
                    <ActivityIndicator size="small" color="#fff" />
                  ) : (
                    <View style={styles.btnContent}>
                      <Plus color="#fff" size={18} style={{ marginRight: 6 }} />
                      <Text style={styles.joinButtonText}>Join Workspace</Text>
                    </View>
                  )}
                </LinearGradient>
              </TouchableOpacity>

              <TouchableOpacity
                style={styles.logoutButton}
                onPress={async () => {
                  await logout();
                  navigation.reset({
                    index: 0,
                    routes: [{ name: 'Login' }],
                  });
                }}
              >
                <LogOut color="#FF6B6B" size={18} style={{ marginRight: 8 }} />
                <Text style={styles.logoutButtonText}>Logout Account</Text>
              </TouchableOpacity>
            </View>
          )}

        </View>
      </LinearGradient>
    </SafeAreaView>
  );
}

const getStyles = (colors: any) => StyleSheet.create({
  outerContainer: {
    flex: 1,
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    backgroundColor: colors.background,
  },
  gradient: {
    flex: 1,
  },
  container: {
    flex: 1,
    padding: 24,
    paddingBottom: 60,
    justifyContent: 'center',
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 8,
  },
  topBarTitle: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#fff',
  },
  header: {
    alignItems: 'center',
    marginBottom: 24,
  },
  backButton: {
    padding: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 12,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#fff',
    letterSpacing: -0.5,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.85)',
    marginTop: 10,
    lineHeight: 24,
    textAlign: 'center',
  },
  loaderContainer: {
    paddingVertical: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loaderText: {
    marginTop: 12,
    fontSize: 14,
    color: '#fff',
  },
  glassCard: {
    backgroundColor: colors.surface,
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 8,
    alignItems: 'center',
  },
  iconWrapper: {
    marginBottom: 24,
  },
  iconGlow: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: colors.tint + '15',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.tint + '30',
  },
  inputContainer: {
    width: '100%',
    marginBottom: 24,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 54,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    backgroundColor: colors.background,
    paddingHorizontal: 16,
  },
  inputIcon: {
    marginRight: 12,
    opacity: 0.8,
  },
  textInput: {
    flex: 1,
    height: '100%',
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
  },
  joinButton: {
    width: '100%',
    height: 52,
    borderRadius: 14,
    overflow: 'hidden',
    marginBottom: 16,
  },
  gradientButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  joinButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    width: '100%',
    borderWidth: 1,
    borderColor: '#FF6B6B30',
    borderRadius: 14,
    marginTop: 8,
  },
  logoutButtonText: {
    color: '#FF6B6B',
    fontSize: 15,
    fontWeight: '600',
  },
});
